name: Train Model with GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Docker
      - name: Build Docker Image
        run: |
          docker build -t marathon-trainer .

      # 3. Ejecutar el contenedor
      - name: Run Docker Container
        run: |
          docker run -v ${{ github.workspace }}/data:/data -v ${{ github.workspace }}/models:/models marathon-trainer
