name: Train Marathon Model

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *' # Cada 6 meses

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar Docker
      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io

      # 3. Construir la imagen Docker
      - name: Build Docker Image
        run: |
          docker build -t marathon-trainer .

      # 4. Ejecutar el contenedor
      - name: Run Training
        run: |
          docker run -v ${{ github.workspace }}/data:/data -v ${{ github.workspace }}/models:/models marathon-trainer
